[package]
name = "chrono-quest"
version.workspace = true
edition.workspace = true

[dependencies]
gstd.workspace = true
chrono-quest-io.workspace = true

[build-dependencies]
gear-wasm-builder.workspace = true
chrono-quest-io.workspace = true

[dev-dependencies]
gtest.workspace = true
