[package]
name = "dictation-battle-app"
version = "0.1.0"
edition = "2021"

[dependencies]
sails-rs = "0.6.2"
scale-info = { version = "2.9", default-features = false, features = [
    "derive",
] }
codec = { package = "parity-scale-codec", version = "3.6", default-features = false }
