[package]
name = "chrono-quest-io"
version.workspace = true
edition.workspace = true

[dependencies]
gstd.workspace = true
gmeta.workspace = true
scale-info.workspace = true
parity-scale-codec.workspace = true
